import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Source_Sans_3 } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "EESL",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sourcesans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${sourceSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
